version: 2.0

env:
  variables:
    CACHE_CONTROL: "86400"
    B3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  installs:
    runtime-versions:
      nodejs: 14
  comands:
    - echo Installing source NPW dependencie
    - npm install
    - npm install -g @angular/cli
build:
  comands:
    - echo Build started
    - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes