version: 2.0

env:
  variables:
    CACHE_CONTROL: "86400"
    B3_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  installs:
    runtime-versions:
      nodejs: 14
  commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
    - echo Build started on `date`
    - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: yes